#!/usr/bin/env bash
#script that will display information about subdomains
dig_function () {
    if [ "$1" ]
    then
        for subdomain in "www" "lb-01" "web-01" "web-02"
        do
            dig "$subdomain"."$1" | grep -A1 'ANSWER SECTION:'
        done
    fi
    return 0
}

dig_function $1
