#!/usr/bin/env bash
#script that transfers a file from our client to a server
# /0-transfer_file some_page.html 8.8.8.8 sylvain /vagrant/private_key

if [ $# == 4 ];
then
scp -i "$4" -o StricHostKeyChecking=no "$1" "$3"@"$2":~/
else
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
