#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine 
ssh ubuntu@18.215.158.133 || cat /var/www/html/index.nginx-debian.html
#echo "Hello World!" >> /var/www/html/index.nginx-debian.html
