#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine 
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
