#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
sudo sed -i 'rewrite ^/redirect_me$ $scheme://youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
location '/redirect_me' {
    return 301 $scheme://youtube.com/watch?v=QH2-TGUlwu4;
}
service nginx start
