#!/usr/bin/env bash
#Configure Nginx server to have a custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' | sudo tee file /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/error-404.html
sudo systemctl start nginx
sudo sed -i 'rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i 'error_page 404 = /var/www/html/error-404.html;' /etc/nginx/sites-available/default
sudo systemctl reload nginx
