#!/usr/bin/env bash
#Configure Nginx server to have a custom 404 page
sudo apt-get update
sudo apt install nginx -y
sudo chown -R ubuntu /var/www/html
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo systemctl start nginx
sudo sed -i 'rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/n/t error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo systemctl reload nginx
