#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo systemctl start nginx
sudo echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '\n\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '\n\tserver_name _;\n\t error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo sed -i '\n\tadd_header X-Served-By \$hostname;' /etc/nginx/sites-available/default
sudo systemctl reload nginx
