#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd.
#only display:
#username
#user id
#Home directory path for the user
for i in /etc/passwd 
do
echo | cut -d":" -f 1,3,6 /etc/passwd 
done