#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd.
#only display:
#username
#user id
#Home directory path for the user
#input="/etc/passwd"
#while IFS= read -r line
#do
#echo "$line" | cut -d":" -f 1,3,6 /etc/passwd 
#done < "$input"
input="/etc/passwd"
while IFS= read -r line
do
  echo "$line" | cut -d":" -f 1,3,6 
done < "$input"
