#!/usr/bin/env bash
#script that displays the visitor IP along with the HTTP status code from the Apache log file.
#Format: IP HTTP_CODE
#input="apache-access.log"
#while IFS="-\" " read -r f1 f2 f3 f4 f5 f6 f7 f8 f9
#do
#echo "$f1 $f8"
#done < "$input"
cat apache-access.log | awk '{print $1,$9}'
